version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  publish:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run:
          name: npm publish
          command: |
            npx semantic-release
workflows:
  build:
    jobs:
      - test
  publish:
    jobs:
      - publish:
#          filters:
#            branches:
#              only: master
          context: GH_TOKEN
