version: 2.1
orbs:
  node: circleci/node@4.2.0
  go: circleci/go@1.6.0

commands:
  set-version:
    steps:
      - run:
          name: read version file and export to APP_VERISON
          command: |
            export APP_VERSION=$(cat .version)
            echo "export APP_VERSION=${APP_VERSION}" >> $BASH_ENV
            echo "read in version ${APP_VERSION}"

jobs:
  get-version:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: export version variable
          command: |
            export APP_VERSION="$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')"
            export NPX_STATUS="${PIPESTATUS[0]} ${PIPESTATUS[1]}"
            if [ ${NPX_STATUS} -ne 0 ]; then
              echo "failed to run semantic release"
              exit ${NPX_STATUS}
            fi
            if [ -z "${APP_VERSION}" ]; then
              echo "no new version detected"
            else
              echo "found next Version ${APP_VERSION}"
            fi
            echo "${APP_VERSION}" > .version
      - persist_to_workspace:
          root: .
          paths:
            - .version
  build:
    docker:
      - image: 'cimg/go:1.14'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - set-version
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: install-tools
          command: |
            go get -u github.com/mitchellh/gox
      - run:
          name: cross compile
          command: |
            if [ -z "${APP_VERSION}" ]; then
              export VERSION="${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
            else
              export VERSION="${APP_VERSION}"
            fi
            gox -ldflags "-X 'main.Version=${VERSION}'" -os="linux darwin windows" -arch="amd64" -output="dist/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}"
            ./dist/go-template-project_linux_amd64 version
      - persist_to_workspace:
          name: save distributions
          root: .
          paths:
            - ./dist
  publish:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            npm install
      - run:
          name: release
          command: |
            npx semantic-release
workflows:
  build-and-publish:
    jobs:
      - get-version
      - build:
          requires:
            - get-version
      - publish:
          filters:
            branches:
              only: master
          context: semantics-release
          requires:
            - build
